### ISSUE TITLE
The CLI expects the user to provide a non-implemented `--override` flag

### ISSUE THREAD

**Issue by nikitawootten-nist** [usnistgov/oscal-cli#127] opened 2023-04-10 18:00 UTC
# Describe the bug

When running operations such as `profile resolve` or `<model> convert` with an output file that already exists, the CLI complains that the file already exists, telling the user to run the command again with an `--overwrite` flag that has not been implemented.

# Who is the bug affecting?

Users of the CLI

# What is affected by this bug?

Any command that produces an output

# When does this occur?

- A command producing an output file is run with an existing file name
- The CLI instructs the user to run again with `--overwrite`
- The user reruns the command specifying `--overwrite` as instructed
- `--overwrite` is treated as an unexpected option

# How do we replicate the issue?

```
$ oscal-cli profile resolve /WORKING/basic-profile.json /WORKING/output-resolved-catalog.json
The provided destination '/WORKING/output-resolved-catalog.json' already exists and the --overwrite option was not provided.

$ oscal-cli profile resolve --overwrite /WORKING/basic-profile.json /WORKING/output-resolved-catalog.json
usage: oscal-cli profile resolve [<options>] <file to resolve> [<destination file>]
    --as <FORMAT>        source format: xml, json, or yaml
 -h,--help               display this help message
    --no-color           do not colorize output
 -q,--quiet              minimize output to include only errors
    --show-stack-trace   display the stack trace associated with an error
 -t,--to <FORMAT>        convert to format: xml, json, or yaml
    --version            display the application version
```

# Expected behavior (i.e. solution)

# Other Comments

Also of note in the expected behavior section the second run shows the help text because `--overwrite` is not an expected argument but does not report this. Following https://github.com/usnistgov/oscal-cli/issues/125, an explicit error message should be added stating that an unexpected flag was provided.

**Comment by david-waltermire-nist** [comment] 2023-06-02 21:11
This is a partial duplicate of #79.

**Comment by aj-stein-nist** [comment] 2023-06-02 21:16
This appears to be a dupe like Dave said, closing for now. If I misunderstood or there is not complete overlap, feel free to reopen this issue and let me know.

**Closed by aj-stein-nist** 2023-06-02 21:16 UTC
Labels: bug
